### ISSUE TITLE
Unable to Run Tests in NetCoreApp2.0

### ISSUE THREAD

**Issue by say25** [telerik/JustMockLite#72]
Running the following in Net472 is fine, switching to NetCoreApp2.0 causes the following exception:

```
Test method *** threw exception: 
System.TypeInitializationException: The type initializer for 'Telerik.JustMock.SecuredReflectionMethods' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Telerik.JustMock.SecuredReflection' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Permissions, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
    at Telerik.JustMock.SecuredReflection.CheckReflectionPermission()
   at Telerik.JustMock.SecuredReflection..cctor()
--- End of inner exception stack trace ---
    at Telerik.JustMock.SecuredReflection.get_HasReflectionPermission()
   at Telerik.JustMock.SecuredReflectionMethods..cctor()
--- End of inner exception stack trace ---
    at Telerik.JustMock.Core.ExpressionUtil.EvaluateExpression(Expression expr)
   at Telerik.JustMock.Core.MocksRepository.ConvertExpressionToCallPattern(Expression expr, CallPattern callPattern)
   at Telerik.JustMock.Core.MocksRepository.Arrange[TMethodMock](Expression expr, Func`1 methodMockFactory)
   at Telerik.JustMock.Core.ProfilerInterceptor.GuardInternal[T](Func`1 guardedAction)
   at *** in ***:line 47
```

**Comment by mihail-vladov** [comment]
Hello Steven,

Could you please share how exactly you are targeting .netcoreapp 2.0? Code sample from the test project and from the project of the assembly under test would be appreciated.
Any other information you think might help us reproduce the problem is welcome.

**Comment by say25** [comment]
Here is a minimal project that should prove the failure

[MinimalProject.zip](https://github.com/telerik/JustMockLite/files/2784122/MinimalProject.zip)

**Comment by say25** [comment]
Should contain.

<details><summary>UnitTestProject.csproj</summary>
<p>

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="1.3.2" />
    <PackageReference Include="MSTest.TestFramework" Version="1.3.2" />
    <PackageReference Include="JustMock" Version="2019.1.115.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Library\Library.csproj" />
  </ItemGroup>

</Project>
```

</p>
</details>

<details><summary>UnitTest1.cs</summary>
<p>

```csharp
using Library;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Telerik.JustMock;

namespace UnitTestProject
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            var dataClass = Mock.Create<IDataClass>();

            Mock.Arrange(() => dataClass.GetData());
        }
    }
}
```

</p>
</details>

<details><summary>Library.csproj</summary>
<p>

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

</Project>

```

</p>
</details>




<details><summary>Library.sln</summary>
<p>

```csharp

Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
VisualStudioVersion = 15.0.28307.271
MinimumVisualStudioVersion = 10.0.40219.1
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Library", "Library\Library.csproj", "{DE7F9802-12C3-4213-8FA7-34D8F91CE843}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "UnitTestProject", "UnitTestProject\UnitTestProject.csproj", "{1539E038-D438-4962-8411-E426E3BF8B96}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{DE7F9802-12C3-4213-8FA7-34D8F91CE843}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{DE7F9802-12C3-4213-8FA7-34D8F91CE843}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{DE7F9802-12C3-4213-8FA7-34D8F91CE843}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{DE7F9802-12C3-4213-8FA7-34D8F91CE843}.Release|Any CPU.Build.0 = Release|Any CPU
		{1539E038-D438-4962-8411-E426E3BF8B96}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{1539E038-D438-4962-8411-E426E3BF8B96}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{1539E038-D438-4962-8411-E426E3BF8B96}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{1539E038-D438-4962-8411-E426E3BF8B96}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {3873B4E5-4625-4E2A-A14D-927DBF610B5B}
	EndGlobalSection
EndGlobal

```

</p>
</details>

**Comment by mihail-vladov** [comment]
Hello Steven,

You should add the NuGet package System.Security.Permissions to your test project and the tests should pass as expected.
We will provide new project templates with the installation of JustMockLite and a documentation article explaining how a .NetCore project should be created.
I hope this information is helpful. Nevertheless, if you have further questions do not hesitate to contact us here or in our [JustMock forum](https://www.telerik.com/forums/justmock).

**Comment by say25** [comment]
That worked! I feel like `System.Security.Permissions` should be a dependency for the `JustMock` NuGet package

**Comment by mihail-vladov** [comment]
Hello Steven,

We have released a new version of the NuGet package that includes a dependency to System.Security.Permissions. Thank you for your cooperation.
